# Railway Deployment Configuration

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment Variables (Set these in Railway Dashboard -> Variables tab)
# GOOGLE_CLOUD_PROJECT_ID=your-actual-project-id  
# GOOGLE_APPLICATION_CREDENTIALS={"type":"service_account",...} # Full JSON content
# FLASK_ENV=production
# FLASK_DEBUG=False
# PORT=8080
